# -*- coding: utf-8 -*-
"""t-sne.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15XzLpBLVvtb6cqGXjZ7a6sKCC0VomE7S
"""

from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive', force_remount=True)



!pip install sklearn
!pip install matplotlib
!pip install numpy

import numpy as np
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE

entity_embedding_path = '/content/drive/My Drive/KGE/TransE_l2_output-6b_0/output-6b_TransE_l2_entity.npy'
relation_embedding_path = '/content/drive/My Drive/KGE/TransE_l2_output-6b_0/output-6b_TransE_l2_relation.npy'

entity_embeddings = np.load(entity_embedding_path)
relation_embeddings = np.load(relation_embedding_path)

# Combine entity and relation embeddings for t-SNE (to plot together)
combined_embeddings = np.vstack([entity_embeddings, relation_embeddings])

# Apply t-SNE dimensionality reduction to 2D
tsne_model = TSNE(n_components=2, random_state=42, perplexity=30, n_iter=1000)
combined_embeddings_2d_tsne = tsne_model.fit_transform(combined_embeddings)

# Get separate t-SNE projections for entities and relations
entity_embeddings_2d_tsne = combined_embeddings_2d_tsne[:len(entity_embeddings)]
relation_embeddings_2d_tsne = combined_embeddings_2d_tsne[len(entity_embeddings):]

# Plot the t-SNE visualization
plt.figure(figsize=(10, 8))

# Plot entity embeddings
plt.scatter(entity_embeddings_2d_tsne[:, 0], entity_embeddings_2d_tsne[:, 1],
            c='blue', label='Entities', alpha=0.6, s=10, edgecolor='k')

# Plot relation embeddings
plt.scatter(relation_embeddings_2d_tsne[:, 0], relation_embeddings_2d_tsne[:, 1],
            c='red', label='Relations', alpha=0.8, s=30, marker='x')

# Titles and labels for better readability
plt.title('t-SNE Visualization of TransE Entity and Relation Embeddings', fontsize=14)
plt.xlabel('t-SNE Dim 1', fontsize=12)
plt.ylabel('t-SNE Dim 2', fontsize=12)

# Add a legend to differentiate between entities and relations
plt.legend(loc='best')

# Save the plot
output_path = '/content/drive/My Drive/KGE/SKGs/tsne_visualization_entities_relations_colored-6b.png'
plt.savefig(output_path, format='png', dpi=300)

# Show the plot (optional)
plt.show()